# Your Name or Company
title: Mikaela Grace 

# Description of your website. This is used for social sharing.
description:  A website written by and about Mikaela Grace.

# A brief blurb about yourself
content: NYC-based software engineer. <br> <br> Prior work in acoustic modeling and detection of emotion in music. 
# <br> Using machine learning to derive meaning from sound. <br>
# Add your social links
social:
  #   - platform: instagram
  #   url: https://instagram.com/_mikaela_grace
  - platform: github
    url: https://github.com/mikaelagrace
  - platform: linkedin
    url: https://linkedin.com/in/mikaelagrace
  - platform: publications
    url: https://ieeexplore.ieee.org/document/8639654
  
# General settings
url: https://mikaela.dev
# baseurl: "/uni" 
markdown: kramdown
sharing_image: paint-background.jpg

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center

